import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ChiefJustice } from '../src/agents/judicial/chief-justice';
import { RulesEngine } from '../src/agents/judicial/rules-engine';
import { KillSwitch } from '../src/agents/judicial/kill-switch';
import { OpenClawAdapter } from '../src/openclaw/adapter';
import { ConstitutionConfig } from '../src/config/models';
import { EventAction, EmotionType, ExecutionEvent } from '../src/schemas/events';
import { ExecutionReport } from '../src/schemas/act';
import { ViolationType } from '../src/schemas/verdict';

// Mock config
const mockConstitution: ConstitutionConfig = {
  version: '1.0',
  judicial: {
    blacklist_commands: ['sudo rm', 'wget', 'curl'],
    token_budget: {
      max_per_task: 1000,
      debate_budget: 1000,
      execution_budget: 2000,
      review_budget: 500
    },
    debate: {
      max_rounds: 3,
      conflict_threshold: 10,
      consensus_threshold: 5,
      min_rounds: 1
    },
    deviation: {
      max_score: 0.3
    }
  },
  security: {
    sandbox_enabled: true,
    allowed_file_extensions: ['.txt', '.ts', '.js', '.md'],
    max_execution_time_seconds: 60,
    max_file_size_mb: 10,
    network_access: 'none'
  },
  rbac: { permissions: [], role_permissions: {} }
};

describe('Judicial Branch Components', () => {

  describe('RulesEngine & Security Net (kill-switch)', () => {
    let rules: RulesEngine;
    beforeEach(() => {
      rules = new RulesEngine(mockConstitution);
    });

    it('should catch dangerous regex commands', () => {
      const tests = [
        { code: 'rm -rf /usr/bin', pass: false },
        { code: 'sudo apt get update', pass: false },
        { code: 'chmod 777 ./malicious.sh', pass: false },
        { code: 'chmod -R 777 /var/log', pass: false },
        { code: 'const fs = require("fs"); fs.unlinkSync("/");', pass: false },
        { code: 'ls -la', pass: true },
        { code: 'wget http://malicious.com', pass: false }, // Caught by blacklist array
        { code: 'charm -rf', pass: true }, // False positive check!
      ];

      for (const t of tests) {
        const result = rules.checkCommand(t.code);
        expect(result.passed).toBe(t.pass);
      }
    });

    it('should generate properly formatted kill report from KillSwitch', async () => {
      const killSwitch = new KillSwitch();
      const verdict = {
        verdict_id: 'v-123',
        act_id: 'act-456',
        constitutional: false,
        ruling: '违宪：使用了高危命令',
        violation_type: ViolationType.BLACKLIST_COMMAND,
        evidence: ['命中正则: rm -rf'],
        created_at: new Date()
      };
      
      const report = await killSwitch.execute(verdict);
      
      expect(report.rollback_success).toBe(true);
      expect(report.killed_processes).toContain('mock_process_act-456');
      expect(report.judgment_document).toContain('UNCONSTITUTIONAL');
      expect(report.judgment_document).toContain('违宪类型: blacklist_command');
      expect(report.judgment_document).toContain('1. 命中正则: rm -rf');
    });
  });

  describe('ChiefJustice & Reviewers (Double Review)', () => {
    let adapter: OpenClawAdapter;
    let chief: ChiefJustice;

    beforeEach(() => {
      adapter = new OpenClawAdapter();
      chief = new ChiefJustice(mockConstitution, adapter, undefined, undefined);
    });

    it('should accurately parse LLM Deviation Score and handle unconstitutional state', async () => {
      // Mock the LLM to return a high deviation (failing) JSON
      vi.spyOn(adapter, 'callLLM').mockResolvedValueOnce({
        content: '```json\n{"score": 0.8, "reason": "完全偏离题意"}\n```',
        rawOutput: ''
      });

      const report: ExecutionReport = {
        act_id: 'act-001',
        overall_status: 'completed',
        task_results: [
          { task_id: 't-1', step_index: 0, status: 'success', output: '我是不相关的内容', tokens_consumed: 5 }
        ],
        total_tokens_consumed: 100,
        execution_time_seconds: 2
      };

      const verdict = await chief.reviewResult('请实现一个倒计时插件', report);
      expect(verdict.constitutional).toBe(false);
      expect(verdict.violation_type).toBe(ViolationType.DEVIATION_EXCEEDED);
      expect(verdict.result_review?.deviation.score).toBe(0.8);
    });

    it('should parse string formatted scores generated by LLM securely', async () => {
      vi.spyOn(adapter, 'callLLM').mockResolvedValueOnce({
        content: '```json\n{"score": "0.4", "reason": "轻微偏离"}\n```',
        rawOutput: ''
      });
      const report: ExecutionReport = {
        act_id: 'act-00x',
        overall_status: 'completed',
        task_results: [
           { task_id: 't-0', step_index: 0, status: 'success', output: '还凑合', tokens_consumed: 5 }
        ],
        total_tokens_consumed: 10,
        execution_time_seconds: 1
      };
      const verdict = await chief.reviewResult('要求', report);
      expect(verdict.constitutional).toBe(false); // max is 0.3
      expect(verdict.result_review?.deviation.score).toBe(0.4);
    });

    it('should emergency fuse on high-risk keywords in execution output via RulesEngine (Bug 44 fix)', async () => {
      const callLLMSpy = vi.spyOn(adapter, 'callLLM');
      const report: ExecutionReport = {
        act_id: 'act-002',
        overall_status: 'completed',
        // Bug 44 fix: blacklist check moved from petition to execution output
        task_results: [
          { task_id: 't-1', step_index: 0, status: 'success', output: '执行了: fs.unlink("/")', tokens_consumed: 5 }
        ],
        total_tokens_consumed: 100,
        execution_time_seconds: 2
      };
      
      const verdict = await chief.reviewResult('帮我操作文件系统', report);
      
      expect(callLLMSpy).not.toHaveBeenCalled();
      expect(verdict.constitutional).toBe(false);
      expect(verdict.violation_type).toBe(ViolationType.BLACKLIST_COMMAND);
      expect(verdict.ruling).toContain('执行产出中发现危险指令');
    });

    it('should catch infinite loop pattern in ProcessReviewer', async () => {
      const execEvent: ExecutionEvent = {
        timestamp: new Date(),
        source_agent: 'sec_engineering',
        target_agent: null,
        action: EventAction.TOOL_CALL,
        emotion: EmotionType.NEUTRAL,
        intensity: 0.5,
        payload: { command: 'echo "hello"' },
        tool_name: 'CodeExecution',
        step_index: 1,
        status: 'success'
      };

      // Emit 4 times
      for (let i = 0; i < 4; i++) {
        const res = await chief.monitorExecution(execEvent);
        expect(res.passed).toBe(true);
      }
      
      // 5th time hits the loopThreshold
      const failingRes = await chief.monitorExecution(execEvent);
      expect(failingRes.passed).toBe(false);
      expect(failingRes.violations.some(v => v.includes(ViolationType.INFINITE_LOOP))).toBe(true);
    });

    it('should throw RESOURCE_EXCEEDED when token budget goes over limit in ProcessReviewer', async () => {
       const execEvent: ExecutionEvent = {
        timestamp: new Date(),
        source_agent: 'sec_engineering',
        target_agent: null,
        action: EventAction.TOOL_CALL,
        emotion: EmotionType.NEUTRAL,
        intensity: 0.5,
        payload: { command: 'echo "hello"', tokens_consumed: 99999 },
        tool_name: 'PythonInterpreter',
        step_index: 1,
        status: 'success'
      };

      const failingRes = await chief.monitorExecution(execEvent);
      expect(failingRes.passed).toBe(false);
      expect(failingRes.violations.some(v => v.includes(ViolationType.RESOURCE_EXCEEDED))).toBe(true);
    });

    it('should strictly emit JudgmentEvent using this.emitEvent with correct payload', async () => {
      const emitSpy = vi.spyOn(chief, 'emitEvent'); // BaseAgent spy
      
      const verdict = {
        verdict_id: 'v-789',
        act_id: 'act-111',
        constitutional: false,
        ruling: '违宪：由于偏离度过高',
        violation_type: ViolationType.DEVIATION_EXCEEDED,
        evidence: ['偏离度 0.9 > 0.3'],
        created_at: new Date()
      };

      const judgmentEvent = await chief.issueJudgment(verdict);
      
      expect(emitSpy).toHaveBeenCalledWith(
        EventAction.UNCONSTITUTIONAL,
        expect.objectContaining({ kill_report: expect.any(Object) }),
        'speaker',
        'act-111'
      );

      expect(judgmentEvent.action).toBe(EventAction.UNCONSTITUTIONAL);
      expect(judgmentEvent.violation_type).toBe(ViolationType.DEVIATION_EXCEEDED);
      expect(judgmentEvent.traceback).toBeDefined(); // KillReport JSON stringified
    });
  });
});
